apiVersion: v1
kind: Service
metadata:
  name: squidproxy
  labels:
    name: squidproxy
    service: squidproxy
spec:
  type: NodePort
  ports:
    - name: http
      port: 31290
      targetPort: http
      nodePort: 3129
  selector:
    service: squidproxy
