apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    name: squid
    service: squid
spec:
  type: NodePort
  ports:
    - name: http
      port: 3129
      targetPort: http
      nodePort: 3129
  selector:
    service: squid
