apiVersion: v1
kind: Service
metadata:
  name: squidproxy
  labels:
    name: squidproxy
    service: squidproxy
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 3129
      nodePort: 31290
  selector:
    service: squidproxy
